/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FinverUI;

import Views.FnvrCatFrm;
import Views.FnvrEditCatFrm;
import java.awt.Color;

/**
 *
 * @author Angel H
 */
public class CategCard extends RoundPanel{
    
    private Color txtColor;
    private FnvrEditCatFrm frm;
    private String nombre;
    private String desc;
    private int id_categ;
    
    public boolean isEdit = false;
    
    
    public CategCard() {
        initComponents();
    }
    
    public CategCard(String nombre, String cat) {
        initComponents();
        this.nombre = nombre;
        this.desc = cat;
        this.lblNombre.setText(nombre);
        this.lblDescrip.setText(cat);
    }
    
      public CategCard(int id, String nombre, String cat, FnvrEditCatFrm frm) {
        initComponents();
        this.id_categ = id;
        this.nombre = nombre;
        this.desc = cat;
        this.frm = frm;
        this.lblNombre.setText(nombre);
        this.lblDescrip.setText(cat);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescrip = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(93, 148, 237));
        setMaximumSize(new java.awt.Dimension(32767, 78));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(93, 148, 237));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 10, 5));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Nombre");
        jPanel1.add(lbl1);

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Descripcion");
        jPanel1.add(lbl2);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Ingreso");
        jPanel1.add(lblNombre);

        lblDescrip.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDescrip.setForeground(new java.awt.Color(255, 255, 255));
        lblDescrip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescrip.setText("$240");
        jPanel1.add(lblDescrip);

        lblIcon.setFont(new java.awt.Font("Segoe Fluent Icons", 1, 36)); // NOI18N
        lblIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        frm.setId_cat(id_categ);
        frm.TXTA_DESCRIP.setText(this.desc);
        frm.TXT_NOMBRE.setText(this.nombre);
        
        
        frm.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl1;
    public javax.swing.JLabel lbl2;
    public javax.swing.JLabel lblDescrip;
    private javax.swing.JLabel lblIcon;
    public javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
