/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FinverUI;

import java.awt.Color;

/**
 *
 * @author Angel H
 */
public class MovimientoCardSlim extends RoundPanel{
    

    public enum Tipo{
        Ingreso, Gasto, Normal
    };
    
    private Tipo aTipo = Tipo.Normal;
    public Tipo getATipo(){
        return aTipo;
    }
    public void setATipo(Tipo aTipo){
        this.aTipo = aTipo;
        if(this.aTipo == Tipo.Ingreso){
            this.lbl1.setForeground(new Color(84, 140, 105));
            this.lbl3.setForeground(new Color(84, 140, 105));
            this.lbl4.setForeground(new Color(84, 140, 105));
            this.lblCant.setForeground(new Color(84, 140, 105));
            this.lblCat.setForeground(new Color(84, 140, 105));
            this.lblTipo.setForeground(new Color(84, 140, 105));
            
            this.lblIcon.setText("");
            this.lblIcon.setForeground(new Color(84, 140, 105));
            this.roundPanel1.setBackground(new Color(190, 227, 204));
            this.jPanel1.setBackground(new Color(190, 227, 204));
        }
        if(this.aTipo == Tipo.Gasto){
            this.lbl1.setForeground(new Color(224, 91, 68));
            this.lbl3.setForeground(new Color(224, 91, 68));
            this.lbl4.setForeground(new Color(224, 91, 68));
            this.lblCant.setForeground(new Color(224, 91, 68));
            this.lblCat.setForeground(new Color(224, 91, 68));
            this.lblTipo.setForeground(new Color(224, 91, 68));
            
            this.lblIcon.setText("");
            this.lblIcon.setForeground(new Color(224, 91, 68));
            
            this.roundPanel1.setBackground(new Color(234, 205, 198));
            this.jPanel1.setBackground(new Color(234, 205, 198));
        }
        repaint();
    }
    
    public MovimientoCardSlim() {
        initComponents();
    }
    
    public MovimientoCardSlim(String cat, double monto, String tipo) {
        initComponents();
        this.lblTipo.setText(tipo);
        this.lblCat.setText(cat);
        this.lblCant.setText(Double.toString(monto));
        if(tipo.equals("Ingreso")) this.setATipo(Tipo.Ingreso);
        else if(tipo.equals("Gasto")) this.setATipo(Tipo.Gasto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new FinverUI.RoundPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblCat = new javax.swing.JLabel();
        lblCant = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 239, 242));
        setMaximumSize(new java.awt.Dimension(32767, 69));

        roundPanel1.setBackground(new java.awt.Color(190, 227, 204));
        roundPanel1.setACornerRadius(30);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 55));
        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 10, 3));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 0, 0));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Tipo");
        jPanel1.add(lbl1);

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(0, 0, 0));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Categoria");
        jPanel1.add(lbl3);

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(0, 0, 0));
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Cantidad");
        jPanel1.add(lbl4);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Ingreso");
        jPanel1.add(lblTipo);

        lblCat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCat.setForeground(new java.awt.Color(0, 0, 0));
        lblCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCat.setText("Transporte");
        jPanel1.add(lblCat);

        lblCant.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCant.setForeground(new java.awt.Color(0, 0, 0));
        lblCant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCant.setText("$240");
        jPanel1.add(lblCant);

        lblIcon.setFont(new java.awt.Font("Segoe Fluent Icons", 0, 18)); // NOI18N
        lblIcon.setForeground(new java.awt.Color(0, 0, 0));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setText("");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl1;
    public javax.swing.JLabel lbl3;
    public javax.swing.JLabel lbl4;
    public javax.swing.JLabel lblCant;
    public javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblIcon;
    public javax.swing.JLabel lblTipo;
    private FinverUI.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
