/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FinverUI;

import java.awt.Color;

/**
 *
 * @author Angel H
 */
public class MovimientoCard extends RoundPanel{
    
    private Color txtColor;

    public enum Tipo{
        Ingreso, Gasto, Normal
    };
    
    private Tipo aTipo = Tipo.Gasto;
    public Tipo getATipo(){
        return aTipo;
    }
    public void setATipo(Tipo aTipo){
        this.aTipo = aTipo;
        if(this.aTipo == Tipo.Ingreso){
            this.lbl1.setForeground(new Color(84, 140, 105));
            this.lbl2.setForeground(new Color(84, 140, 105));
            this.lbl3.setForeground(new Color(84, 140, 105));
            this.lbl4.setForeground(new Color(84, 140, 105));
            this.lblCant.setForeground(new Color(84, 140, 105));
            this.lblCate.setForeground(new Color(84, 140, 105));
            this.lblFecha.setForeground(new Color(84, 140, 105));
            this.lblTipo.setForeground(new Color(84, 140, 105));
            
            this.lblIcon.setText("");
            this.lblIcon.setForeground(new Color(84, 140, 105));
            this.setBackground(new Color(190, 227, 204));
        }else if(this.aTipo == Tipo.Normal){
            this.lbl1.setForeground(new Color(79, 115, 211));
            this.lbl2.setForeground(new Color(79, 115, 211));
            this.lbl3.setForeground(new Color(79, 115, 211));
            this.lbl4.setForeground(new Color(79, 115, 211));
            this.lblCant.setForeground(new Color(79, 115, 211));
            this.lblCate.setForeground(new Color(79, 115, 211));
            this.lblFecha.setForeground(new Color(79, 115, 211));
            this.lblTipo.setForeground(new Color(79, 115, 211));
            
            this.lblIcon.setText("");
            this.lblIcon.setForeground(new Color(79, 115, 211));
            
            this.setBackground(new Color(193, 221, 254));
        }else{
            this.lbl2.setVisible(false);
            this.lblFecha.setVisible(false);
        }
        repaint();
    }
    
    public MovimientoCard() {
        initComponents();
    }
    
    public MovimientoCard(int id_cat, double monto, String fecha, String tipo) {
        initComponents();
        this.lblTipo.setText(tipo);
        this.lblFecha.setText(fecha);
        this.lblCate.setText(Integer.toString(id_cat));
        this.lblCant.setText(Double.toString(monto));
        if(tipo.equals("Ingreso")) this.setATipo(Tipo.Ingreso);
        else if(tipo.equals("Gasto")) this.setATipo(Tipo.Normal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lblPresup5 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblCate = new javax.swing.JLabel();
        lblCant = new javax.swing.JLabel();
        btnDetalles = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(190, 227, 204));
        setMaximumSize(new java.awt.Dimension(32767, 62));

        jPanel1.setBackground(null);
        jPanel1.setLayout(new java.awt.GridLayout(2, 6, 10, 10));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl1.setForeground(this.txtColor);
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Tipo");
        jPanel1.add(lbl1);

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl2.setForeground(this.txtColor);
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Fecha");
        jPanel1.add(lbl2);

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl3.setForeground(this.txtColor);
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Categoria");
        jPanel1.add(lbl3);

        lbl4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl4.setForeground(this.txtColor);
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Cantidad");
        jPanel1.add(lbl4);

        lblPresup5.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblPresup5.setForeground(new java.awt.Color(84, 140, 105));
        lblPresup5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblPresup5);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblTipo.setForeground(this.txtColor);
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Ingreso");
        jPanel1.add(lblTipo);

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFecha.setForeground(this.txtColor);
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("$240");
        jPanel1.add(lblFecha);

        lblCate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCate.setForeground(this.txtColor);
        lblCate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCate.setText("$240");
        jPanel1.add(lblCate);

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCant.setForeground(this.txtColor);
        lblCant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCant.setText("$240");
        jPanel1.add(lblCant);

        btnDetalles.setText("Detalles");
        jPanel1.add(btnDetalles);

        lblIcon.setFont(new java.awt.Font("Segoe Fluent Icons", 1, 36)); // NOI18N
        lblIcon.setForeground(this.txtColor);
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDetalles;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl1;
    public javax.swing.JLabel lbl2;
    public javax.swing.JLabel lbl3;
    public javax.swing.JLabel lbl4;
    public javax.swing.JLabel lblCant;
    public javax.swing.JLabel lblCate;
    public javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIcon;
    public javax.swing.JLabel lblPresup5;
    public javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
