/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FinverUI;

/**
 *
 * @author Angel H
 */
public class ResumenCard extends javax.swing.JPanel {

    /**
     * Creates new form ResumenCard
     */
    public ResumenCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPresup = new javax.swing.JLabel();
        statusBar1 = new FinverUI.StatusBar();
        jLabel13 = new javax.swing.JLabel();
        lblGasto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 239, 242));
        setMaximumSize(new java.awt.Dimension(32767, 52));

        lblPresup.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPresup.setForeground(new java.awt.Color(97, 169, 125));
        lblPresup.setText("$0000");

        statusBar1.setBackground(new java.awt.Color(187, 187, 219));
        statusBar1.setForeground(new java.awt.Color(74, 98, 192));
        statusBar1.setABarColor(new java.awt.Color(74, 98, 192));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(74, 98, 192));
        jLabel13.setText("Transporte");

        lblGasto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblGasto.setForeground(new java.awt.Color(74, 98, 192));
        lblGasto.setText("$0000 de");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(lblGasto)
                        .addGap(18, 18, 18)
                        .addComponent(lblPresup)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblPresup)
                    .addComponent(lblGasto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    public javax.swing.JLabel lblGasto;
    public javax.swing.JLabel lblPresup;
    private FinverUI.StatusBar statusBar1;
    // End of variables declaration//GEN-END:variables
}
