/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FinverUI;

import java.awt.Dimension;

/**
 *
 * @author Angel H
 */
public class StatusBar extends RoundPanel {

    
    private int aPorcent = 80;
    public int getAPorcent(){
        return aPorcent;
    }
    public void setAPorcent(int aPorcent){
        this.aPorcent = aPorcent;
        this.Progresbar.setPreferredSize(new Dimension((this.aPorcent * this.getWidth())/100, this.getHeight()));
        this.Progresbar.revalidate();
        this.Progresbar.repaint();
        repaint();
   }
    
    private java.awt.Color aBarColor = new java.awt.Color(237,237,237);
    public java.awt.Color getABarColor(){
        return aBarColor;
    }
    public void setABarColor(java.awt.Color aBarColor){
        this.aBarColor = aBarColor;
        this.Progresbar.setBackground(aBarColor);
        repaint();
    }
    
    /**
     * Creates new form StatusBar
     */
    public StatusBar() {
        initComponents();
        this.setACornerRadius(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new FinverUI.RoundPanel();
        Progresbar = new FinverUI.RoundPanel();

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(65, 67, 159));

        Progresbar.setBackground(new java.awt.Color(237, 237, 237));
        Progresbar.setACornerRadius(30);

        javax.swing.GroupLayout ProgresbarLayout = new javax.swing.GroupLayout(Progresbar);
        Progresbar.setLayout(ProgresbarLayout);
        ProgresbarLayout.setHorizontalGroup(
            ProgresbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );
        ProgresbarLayout.setVerticalGroup(
            ProgresbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Progresbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Progresbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FinverUI.RoundPanel Progresbar;
    private FinverUI.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
