/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.UIManager;

/**
 *
 * @author Angel H
 */
public class FnvrMainFrm extends javax.swing.JFrame {

    /**
     * Creates new form FnvrMainFrm
     */
    public FnvrMainFrm() {
        initComponents();
        
        FlatMacLightLaf.setup();
        getRootPane().putClientProperty("FlatLaf.fullWindowContent", true);
        
        
         UIManager.put("TitlePane.buttonSize", new Dimension(50, 47)); 
        UIManager.put("JRootPane.titleBarHeight", 45); 
        UIManager.put("TitlePane.buttonMaximizedHeight", 45); 
        
        UIManager.put("TitlePane.buttonForeground", new Color(65, 67, 159));
        UIManager.put("TitlePane.buttonHoverForeground", Color.WHITE);
        UIManager.put("TitlePane.buttonHoverBackground", new Color(104,123,255));
        UIManager.put("TitlePane.buttonPressedBackground", new Color(104,123,255));
        UIManager.put("TitlePane.closeHoverBackground", new Color(104,123,255));
        UIManager.put("TitlePane.closePressedBackground", new Color(104,123,255));
        
        FlatLightLaf.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MainMenu = new FinverUI.RoundPanel();
        cerrarBtn = new FinverUI.MenuButton();
        btnInicio = new FinverUI.MenuButton();
        btnMovimiento = new FinverUI.MenuButton();
        btnCateg = new FinverUI.MenuButton();
        btnReport = new FinverUI.MenuButton();
        roundPanel1 = new FinverUI.RoundPanel();
        jLabel1 = new javax.swing.JLabel();
        UserPanel = new FinverUI.RoundPanel();
        TitlePanel = new FinverUI.RoundPanel();
        accountBtn1 = new FinverUI.AccountBtn();
        contPanel = new FinverUI.RoundPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(65, 67, 159));

        MainMenu.setBackground(new java.awt.Color(65, 67, 159));
        MainMenu.setACornerRadius(0);

        cerrarBtn.setBackground(new java.awt.Color(65, 67, 159));
        cerrarBtn.setAFuente(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cerrarBtn.setAIconSize(20);
        cerrarBtn.setAMouseEnter(new java.awt.Color(87, 109, 219));
        cerrarBtn.setATexto("Cerrar Sesion");
        cerrarBtn.setATextoIcono("");

        btnInicio.setBackground(new java.awt.Color(65, 67, 159));
        btnInicio.setAFuente(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setAIconSize(20);
        btnInicio.setAMouseEnter(new java.awt.Color(87, 109, 219));
        btnInicio.setATexto("Inicio");
        btnInicio.setATextoIcono("");

        btnMovimiento.setBackground(new java.awt.Color(65, 67, 159));
        btnMovimiento.setAFuente(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMovimiento.setAIconSize(20);
        btnMovimiento.setAMouseEnter(new java.awt.Color(87, 109, 219));
        btnMovimiento.setATexto("Movimientos");
        btnMovimiento.setATextoIcono("");

        btnCateg.setBackground(new java.awt.Color(65, 67, 159));
        btnCateg.setAFuente(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCateg.setAIconSize(20);
        btnCateg.setAMouseEnter(new java.awt.Color(87, 109, 219));
        btnCateg.setATexto("Categorias");
        btnCateg.setATextoIcono("");

        btnReport.setBackground(new java.awt.Color(65, 67, 159));
        btnReport.setAFuente(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReport.setAIconSize(20);
        btnReport.setAMouseEnter(new java.awt.Color(87, 109, 219));
        btnReport.setATexto("Reporte");
        btnReport.setATextoIcono("");

        roundPanel1.setBackground(new java.awt.Color(68, 75, 161));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FnvrLogo80x80.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cerrarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCateg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(cerrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        UserPanel.setBackground(new java.awt.Color(223, 223, 243));
        UserPanel.setACornerRadius(15);

        TitlePanel.setBackground(new java.awt.Color(223, 223, 243));

        accountBtn1.setBackground(new java.awt.Color(213, 213, 245));
        accountBtn1.setACornerRadius(30);
        accountBtn1.setAFuente(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accountBtn1.setAIconSize(20);
        accountBtn1.setAMouseEnter(new java.awt.Color(187, 187, 219));
        accountBtn1.setAMouseExit(new java.awt.Color(213, 213, 245));
        accountBtn1.setATextColor(new java.awt.Color(68, 75, 161));
        accountBtn1.setATexto("Mi Perfil");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(accountBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contPanel.setBackground(new java.awt.Color(223, 223, 243));

        javax.swing.GroupLayout contPanelLayout = new javax.swing.GroupLayout(contPanel);
        contPanel.setLayout(contPanelLayout);
        contPanelLayout.setHorizontalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );
        contPanelLayout.setVerticalGroup(
            contPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(UserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(UserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FnvrMainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FinverUI.RoundPanel MainMenu;
    private javax.swing.JPanel MainPanel;
    private FinverUI.RoundPanel TitlePanel;
    private FinverUI.RoundPanel UserPanel;
    private FinverUI.AccountBtn accountBtn1;
    public FinverUI.MenuButton btnCateg;
    public FinverUI.MenuButton btnInicio;
    public FinverUI.MenuButton btnMovimiento;
    public FinverUI.MenuButton btnReport;
    public FinverUI.MenuButton cerrarBtn;
    public FinverUI.RoundPanel contPanel;
    private javax.swing.JLabel jLabel1;
    private FinverUI.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
