/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

/**
 *
 * @author Angel H
 */
public class FvnrHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form FvnrHomePanel
     */
    public FvnrHomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new FinverUI.RoundPanel();
        jLabel2 = new javax.swing.JLabel();
        ProgresoBar = new FinverUI.StatusBar();
        gastoTotalLbl = new javax.swing.JLabel();
        presupTotalLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnIngreso = new FinverUI.AccountBtn();
        btnGasto = new FinverUI.AccountBtn();
        btnReporte = new FinverUI.AccountBtn();
        roundPanel2 = new FinverUI.RoundPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        IndResumPnl = new javax.swing.JPanel();
        resumenCard2 = new FinverUI.ResumenCard();
        resumenCard7 = new FinverUI.ResumenCard();
        roundPanel3 = new FinverUI.RoundPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMov = new javax.swing.JPanel();
        movimientoCardSlim1 = new FinverUI.MovimientoCardSlim();
        movimientoCardSlim2 = new FinverUI.MovimientoCardSlim();
        movimientoCardSlim3 = new FinverUI.MovimientoCardSlim();

        setBackground(new java.awt.Color(223, 223, 243));
        setPreferredSize(new java.awt.Dimension(850, 591));

        roundPanel1.setBackground(new java.awt.Color(74, 98, 192));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mes de Marzo");

        ProgresoBar.setAPorcent(49);

        gastoTotalLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gastoTotalLbl.setForeground(new java.awt.Color(255, 227, 227));
        gastoTotalLbl.setText("$0000");

        presupTotalLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        presupTotalLbl.setForeground(new java.awt.Color(199, 255, 248));
        presupTotalLbl.setText("$0000");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Has gastado:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tu periodo del");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tu Presupuesto:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("31 de Marzo 2026");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hasta el");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2 de Marzo 2026");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tu avance se ve asi.");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Resumen de periodo");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProgresoBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(presupTotalLbl)
                            .addComponent(gastoTotalLbl))))
                .addGap(96, 96, 96))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(presupTotalLbl)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(gastoTotalLbl)
                            .addComponent(jLabel9)))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ProgresoBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 36, 62));
        jLabel1.setText("Buenas Tardes");

        jPanel1.setBackground(null);
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        btnIngreso.setBackground(new java.awt.Color(79, 115, 211));
        btnIngreso.setACornerRadius(20);
        btnIngreso.setAFuente(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnIngreso.setAIconSize(35);
        btnIngreso.setAMouseEnter(new java.awt.Color(68, 75, 161));
        btnIngreso.setAMouseExit(new java.awt.Color(79, 115, 211));
        btnIngreso.setATexto("Registrar Ingreso");
        btnIngreso.setATextoIcono("");
        jPanel1.add(btnIngreso);

        btnGasto.setBackground(new java.awt.Color(79, 115, 211));
        btnGasto.setACornerRadius(20);
        btnGasto.setAFuente(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnGasto.setAIconSize(34);
        btnGasto.setAMouseEnter(new java.awt.Color(68, 75, 161));
        btnGasto.setAMouseExit(new java.awt.Color(79, 115, 211));
        btnGasto.setATexto("Registrar Gasto");
        btnGasto.setATextoIcono("");
        jPanel1.add(btnGasto);

        btnReporte.setBackground(new java.awt.Color(79, 115, 211));
        btnReporte.setACornerRadius(20);
        btnReporte.setAFuente(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnReporte.setAIconSize(34);
        btnReporte.setAMouseEnter(new java.awt.Color(68, 75, 161));
        btnReporte.setAMouseExit(new java.awt.Color(79, 115, 211));
        btnReporte.setATexto("Reporte");
        btnReporte.setATextoIcono("");
        jPanel1.add(btnReporte);

        roundPanel2.setBackground(new java.awt.Color(236, 239, 242));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(74, 98, 192));
        jLabel12.setText("Resumen Individual");

        jScrollPane1.setBackground(new java.awt.Color(187, 187, 219));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        IndResumPnl.setBackground(new java.awt.Color(236, 239, 242));
        IndResumPnl.setLayout(new javax.swing.BoxLayout(IndResumPnl, javax.swing.BoxLayout.Y_AXIS));
        IndResumPnl.add(resumenCard2);
        IndResumPnl.add(resumenCard7);

        jScrollPane1.setViewportView(IndResumPnl);

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        roundPanel3.setBackground(new java.awt.Color(236, 239, 242));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(74, 98, 192));
        jLabel13.setText("Ultimos Movimientos");

        jScrollPane2.setBackground(new java.awt.Color(187, 187, 219));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        listMov.setBackground(new java.awt.Color(236, 239, 242));
        listMov.setLayout(new javax.swing.BoxLayout(listMov, javax.swing.BoxLayout.Y_AXIS));

        movimientoCardSlim1.setATipo(FinverUI.MovimientoCardSlim.Tipo.Gasto);
        listMov.add(movimientoCardSlim1);

        movimientoCardSlim2.setATipo(FinverUI.MovimientoCardSlim.Tipo.Ingreso);
        listMov.add(movimientoCardSlim2);

        movimientoCardSlim3.setATipo(FinverUI.MovimientoCardSlim.Tipo.Ingreso);
        listMov.add(movimientoCardSlim3);

        jScrollPane2.setViewportView(listMov);

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2))
                .addGap(23, 23, 23))
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IndResumPnl;
    public FinverUI.StatusBar ProgresoBar;
    private FinverUI.AccountBtn btnGasto;
    private FinverUI.AccountBtn btnIngreso;
    private FinverUI.AccountBtn btnReporte;
    public javax.swing.JLabel gastoTotalLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel listMov;
    private FinverUI.MovimientoCardSlim movimientoCardSlim1;
    private FinverUI.MovimientoCardSlim movimientoCardSlim2;
    private FinverUI.MovimientoCardSlim movimientoCardSlim3;
    public javax.swing.JLabel presupTotalLbl;
    private FinverUI.ResumenCard resumenCard2;
    private FinverUI.ResumenCard resumenCard7;
    private FinverUI.RoundPanel roundPanel1;
    private FinverUI.RoundPanel roundPanel2;
    private FinverUI.RoundPanel roundPanel3;
    // End of variables declaration//GEN-END:variables
}
