/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controles;

/**
 *
 * @author Angel H
 */
public class MenuButton extends javax.swing.JPanel {
    
    private String aTextoIcono;
    public String getATextoIcono(){
        return aTextoIcono;
    }
    public void setATextoIcono(String textoIcono){
        this.aTextoIcono = textoIcono;
        this.lblIcon.setText(textoIcono);
        repaint();
    }
    
    private String aTexto;
    public String getATexto(){
        return aTexto;
    }
    public void setATexto(String texto){
        this.aTextoIcono = texto;
        this.lblInfo.setText(texto);
        this.lblInfo.setForeground(java.awt.Color.WHITE);
        repaint();
    }
    
    private int aIconSize;
    public int getAIconSize(){
        return aIconSize;
    };
    public void setAIconSize(int iconSize){
        this.aIconSize = iconSize;
        this.lblIcon.setFont(new java.awt.Font("Segoe Fluent Icons", 1, iconSize));
        repaint();
    }
    
    private java.awt.Font aFuente;
    public java.awt.Font getAFuente(){
        return aFuente;
    }
    public void setAFuente(java.awt.Font aFuente){
        this.aFuente = aFuente;
        this.lblInfo.setFont(aFuente);
        repaint();
    }
    
    private java.awt.Color aMouseEnter;
    public java.awt.Color getAMouseEnter(){
        return aMouseEnter;
    }
    public void setAMouseEnter(java.awt.Color aMouseEnter){
        this.aMouseEnter = aMouseEnter;
    }
    
    public void MouseEnterColor(){
        
    }
    /**
     * Creates new form MenuButton
     */
    public MenuButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(63, 72, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        lblIcon.setFont(new java.awt.Font("Segoe Fluent Icons", 1, 24)); // NOI18N
        lblIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setText("Button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(aMouseEnter);
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(null);
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
